[package]
name = "IpLogger"
version = "0.1.0"
edition = "2024"
license = "MIT"

[dependencies]
eframe = "0.26"
egui = "0.26"
chrono = "0.4"
reqwest = { version = "0.11", features = ["blocking", "json"] }
serde_json = "1"
rfd = "0.14"

[profile.dev]
opt-level = 0
debug = true
